FROM tiangolo/uwsgi-nginx-flask:flask

RUN mkdir /home/dockeruser
RUN chmod 777 /home/dockeruser
ENV HOME=/home/dockeruser

RUN apt-get update

ADD ../requirements /code_buildtime_tmp/requirements
WORKDIR /code_buildtime_tmp
RUN pip3 install -q -r requirements.txt

ADD . /code_buildtime_snapshot
WORKDIR /
ENV PYTHONPATH=/code_buildtime_snapshot
ENTRYPOINT ["python3", "app.py"]