version: '3'
services:
  authentication-building-block:
    image: rokwire/authentication-building-block:latest
    build:
      context: ../
      dockerfile: authservice/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
